### PR TITLE
Unify music window

### PR DESCRIPTION
**Pull request by notspiff**
Hi, this is my work so far for unifying the music files/nav library like for videos.

i send the pull here so we can hopefully avoid all the goons. not sure if you have any interest but you are the only one i can think of who might have.

keep in mind that this is mostly moving code around, cosmetics are not the focus. we can always address those as well but please let's stay focused on the functionality for now.

there is still some context menu cleaning to be done but damn we need a better system for that. it always turns into horrible spaghetti code. other than that i have tested most things and they seem to work (scans, deletion etc).

the base window is of questionable use now, like for videos. but step by step..

### CODE REVIEW

**Comment by Montellese** [comment]
Cool thanks. I will take a closer look sometime this week (hopefully tomorrow).
I'm certainly interested as it's the one major inconsistency between the video and music library integration right now. Matthias might be interested as well as he has done quite a bit of work in the library area lately (like the library node support for the music section).

**Comment by notspiff** [comment]
@vdrfan

**Comment by Montellese** [comment]
Yup it's @mkortstiege.

I've gone through all commits except for the context menu ones (which are a bit more complex) and only spotted a few minor things. Great work.

**Comment by Montellese** [comment]
Before I forget this probably also needs adjustments in Confluence:
* MyMusicSongs.xml needs to be merged with MyMusicNav.xml
* The "Files Mode" / "Library Mode" button in the side menu can be removed.

**Comment by mkortstiege** [comment]
Nice! I think `mymusic.startwindow` can be nuked entirely as well? Will give it a try over the weekend and report back.

**Comment by Montellese** [comment]
@mkortstiege: I thought that as well at first but it can store a path to any library node like `Albums` or `Artists` etc.

**Comment by mkortstiege** [comment]
Oh, makes sense now. Just did a quick grep and noticed that settings has no label and that there's no obvious video counterpart. Thanks for explaining.

**Comment by ronie** [comment]
changes for confluence: https://github.com/ronie/xbmc/commit/99d0a39eeb85c07d99ec21b8ca473e5f5e40ff25

**Comment by Montellese** [comment]
Once again thanks a lot for your work on this. I finally found the time to rebase it and PR it against master at https://github.com/xbmc/xbmc/pull/8011.

**Pull request closed without merging**
